"""estudios_y_protocolos_inmutables

Revision ID: 9d634fbf4119
Revises: cd9126d57720
Create Date: 2026-07-31 01:28:52.137120
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9d634fbf4119'
down_revision: str | None = 'cd9126d57720'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=64), nullable=False),
    sa.Column('titulo', sa.String(length=256), nullable=False),
    sa.Column('patrocinador', sa.String(length=120), nullable=False),
    sa.Column('fase', sa.String(length=64), nullable=False),
    sa.Column('patologia', sa.String(length=120), nullable=False),
    sa.Column('escenario_clinico', sa.String(length=120), nullable=False),
    sa.Column('linea_tratamiento', sa.String(length=64), nullable=False),
    sa.Column('centro_atencion', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'EN_REVISION', 'VIGENTE', 'SUSPENDIDO', 'CERRADO', 'ARCHIVADO', name='estado_estudio_enum'), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('investigador_principal_id', sa.Uuid(), nullable=True),
    sa.Column('coordinador_id', sa.Uuid(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coordinador_id'], ['usuarios.id'], name=op.f('fk_estudios_coordinador_id_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigador_principal_id'], ['usuarios.id'], name=op.f('fk_estudios_investigador_principal_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estudios'))
    )
    op.create_index(op.f('ix_estudios_codigo_interno'), 'estudios', ['codigo_interno'], unique=True)
    op.create_index(op.f('ix_estudios_disponible'), 'estudios', ['disponible'], unique=False)
    op.create_index(op.f('ix_estudios_estado'), 'estudios', ['estado'], unique=False)
    op.create_index(op.f('ix_estudios_patologia'), 'estudios', ['patologia'], unique=False)
    op.create_table('cohortes_estudios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('estudio_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('biomarcadores_requeridos', sa.JSON(), nullable=False),
    sa.Column('meta_reclutamiento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], name=op.f('fk_cohortes_estudios_estudio_id_estudios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohortes_estudios'))
    )
    op.create_index(op.f('ix_cohortes_estudios_estudio_id'), 'cohortes_estudios', ['estudio_id'], unique=False)
    op.create_table('versiones_protocolo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('estudio_id', sa.Uuid(), nullable=False),
    sa.Column('numero_version', sa.String(length=32), nullable=False),
    sa.Column('descripcion_cambios', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'EN_REVISION', 'VIGENTE', 'REEMPLAZADA', 'ARCHIVADA', name='estado_version_protocolo_enum'), nullable=False),
    sa.Column('es_vigente', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creada_por_id', sa.Uuid(), nullable=True),
    sa.Column('publicada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publicada_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creada_por_id'], ['usuarios.id'], name=op.f('fk_versiones_protocolo_creada_por_id_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], name=op.f('fk_versiones_protocolo_estudio_id_estudios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publicada_por_id'], ['usuarios.id'], name=op.f('fk_versiones_protocolo_publicada_por_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versiones_protocolo')),
    sa.UniqueConstraint('estudio_id', 'numero_version', name='uq_estudio_version_numero')
    )
    op.create_index(op.f('ix_versiones_protocolo_es_vigente'), 'versiones_protocolo', ['es_vigente'], unique=False)
    op.create_index(op.f('ix_versiones_protocolo_estado'), 'versiones_protocolo', ['estado'], unique=False)
    op.create_index(op.f('ix_versiones_protocolo_estudio_id'), 'versiones_protocolo', ['estudio_id'], unique=False)
    op.create_table('criterios_manuales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('INCLUSION', 'EXCLUSION', name='tipo_criterio_enum'), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('codigo_criterio', sa.String(length=32), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('seccion_fuente', sa.String(length=120), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versiones_protocolo.id'], name=op.f('fk_criterios_manuales_version_id_versiones_protocolo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_criterios_manuales'))
    )
    op.create_index(op.f('ix_criterios_manuales_tipo'), 'criterios_manuales', ['tipo'], unique=False)
    op.create_index(op.f('ix_criterios_manuales_version_id'), 'criterios_manuales', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_criterios_manuales_version_id'), table_name='criterios_manuales')
    op.drop_index(op.f('ix_criterios_manuales_tipo'), table_name='criterios_manuales')
    op.drop_table('criterios_manuales')
    op.drop_index(op.f('ix_versiones_protocolo_estudio_id'), table_name='versiones_protocolo')
    op.drop_index(op.f('ix_versiones_protocolo_estado'), table_name='versiones_protocolo')
    op.drop_index(op.f('ix_versiones_protocolo_es_vigente'), table_name='versiones_protocolo')
    op.drop_table('versiones_protocolo')
    op.drop_index(op.f('ix_cohortes_estudios_estudio_id'), table_name='cohortes_estudios')
    op.drop_table('cohortes_estudios')
    op.drop_index(op.f('ix_estudios_patologia'), table_name='estudios')
    op.drop_index(op.f('ix_estudios_estado'), table_name='estudios')
    op.drop_index(op.f('ix_estudios_disponible'), table_name='estudios')
    op.drop_index(op.f('ix_estudios_codigo_interno'), table_name='estudios')
    op.drop_table('estudios')
    # ### end Alembic commands ###
