"""agregar_roles_usuario

Revision ID: cd9126d57720
Revises: 20260717_0002
Create Date: 2026-07-31 01:26:25.473189
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'cd9126d57720'
down_revision: str | None = '20260717_0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('rol', sa.Enum('ADMINISTRADOR', 'INVESTIGADOR_PRINCIPAL', 'MEDICO_INVESTIGADOR', 'ENFERMERIA', 'COORDINADOR', 'AUDITOR', name='rol_usuario_enum'), nullable=False),
    sa.Column('asignado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asignado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por_id'], ['usuarios.id'], name=op.f('fk_usuario_roles_asignado_por_id_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_usuario_roles_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario_roles'))
    )
    op.create_index(op.f('ix_usuario_roles_rol'), 'usuario_roles', ['rol'], unique=False)
    op.create_index(op.f('ix_usuario_roles_usuario_id'), 'usuario_roles', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_roles_usuario_id'), table_name='usuario_roles')
    op.drop_index(op.f('ix_usuario_roles_rol'), table_name='usuario_roles')
    op.drop_table('usuario_roles')
    # ### end Alembic commands ###
